# Generated by Django 3.0.6 on 2020-08-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('not-started', 'Not started'), ('in-progress', 'In progress'), ('stuck', 'Stuck'), ('done', 'Done')], default='not-started', max_length=12),
        ),
    ]
